
project_id = "mgjodiqecnnltsgorife"

[[functions]]
name = "check-email-exists"
verify_jwt = false

[[functions]]
name = "create-client-user"
verify_jwt = false

[[functions]]
name = "generate-client-password"
verify_jwt = false

[[functions]]
name = "reset-password"
verify_jwt = false

[[functions]]
name = "send-client-invitation"
verify_jwt = false

[[functions]]
name = "send-deletion-email"
verify_jwt = false

[[functions]]
name = "send-email"
verify_jwt = false

[[functions]]
name = "send-invitation"
verify_jwt = false

[[functions]]
name = "send-recovery-confirmation"
verify_jwt = false

[[functions]]
name = "setup-2fa"
verify_jwt = false

[[functions]]
name = "verify-recovery-token"
verify_jwt = false

[[functions]]
name = "validate-url"
verify_jwt = false
